algoritmo "ParOuImpar"
// =============================================================
// Algoritmo para verificar se um valor e PAR ou IMPAR
//
// AUTOR: Gustavo Guanabara
// Curso COMPLETO disponivel GRATIS no site www.cursoemvideo.com
// =============================================================
var
N: Inteiro
inicio
Escreva("Digite um número qualquer: ")
Leia(N)
Se (N % 2 = 0) entao
   EscrevaL("O número ", N, " é PAR")
senao
   EscrevaL("O número ", N, " é ÍMPAR")
FimSe
fimalgoritmo
